server:
  port: 8761

spring:
  application:
    name: eureka-server
  output:
    ansi:
      enabled: always

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false