server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: mongo

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://eureka2:8761/eureka'

pcurl:
  pc:8080