server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka, http://eureka2:8761/eureka

zuul:
  ignoredServices: "*"
  routes:
    pc: /pc/**
    po: /po/**